include("head.jl")
include("util.jl")
include("key.jl")
include("code.jl")
include("crypt.jl")
include("democode.jl")
include("democrypt.jl")
include("text.jl")
include("print.jl")
include("demo.jl")

stepwisedemo(27)
singlekeydemo(27)
# k = randomkey(15)
# testspin(k,100000)